### ISSUE TITLE
Re: #278

### ISSUE THREAD

**Issue by k-byun** [ankneis/ankneis#1]
Hi Allison,
Not sure if I am asking this in the right place but do you know when the Project Roadmap Layout will become GA, or is there a way to try out the beta version of it?  It's indicated to be Private Beta so if there is anyway that I can be in the Private Beta group, can you please share that with me?  I heard about this Roadmap during the Github Universe '22, and was pretty excited about it to try it out but I can't find a way to try it out.

Thanks,

**Comment by k-byun** [comment]
@ankneis: if there is another source that I need to contact to get some more information, please let me know.  NVM, I see the GitHub roadmap had the section updated to join the waitlist.  Thanks.

**Comment by ankneis** [comment]
@k-byun Sorry for the late reply here! Glad you were able to find the link to join the waitlist: https://github.com/github/roadmap/issues/278!

**Comment by k-byun** [comment]
I couldn't join the waiting list since I didnt' have organization in the github but then found out a few days later that creating a organization is free in GitHub.
I just created a dummy org to try this out.  Thanks!
